server:
  port: 8083
spring:
  application:
    name: SLOT-SERVICE
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
     import: configserver:http://localhost:8087